/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YojanaSlugRouteImport } from './routes/yojana.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YojanaSlugRoute = YojanaSlugRouteImport.update({
  id: '/yojana/$slug',
  path: '/yojana/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/yojana/$slug': typeof YojanaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/yojana/$slug': typeof YojanaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/yojana/$slug': typeof YojanaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/yojana/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/yojana/$slug'
  id: '__root__' | '/' | '/yojana/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YojanaSlugRoute: typeof YojanaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yojana/$slug': {
      id: '/yojana/$slug'
      path: '/yojana/$slug'
      fullPath: '/yojana/$slug'
      preLoaderRoute: typeof YojanaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YojanaSlugRoute: YojanaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
